services:
  - type: web
    name: guias-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MONGODB_URI
        fromEnv: MONGODB_URI
      - key: SECRET_KEY
        fromEnv: SECRET_KEY
      - key: MAIL_SERVER
        value: "smtp.gmail.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        fromEnv: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromEnv: MAIL_PASSWORD
      - key: MAIL_USE_TLS
        value: "True"